### ISSUE TITLE
The "SITE CHMOD" FTP command seems not working

### ISSUE THREAD

**Issue by Str1ker17** [kingk85/uFTP#11]
Hello. First, I want to thank a developer for this FTP server, which is able to run even in a custom environment where OpenSSH and Dropbear does not!

However, the "SITE CHMOD" command seems not working. For example:
```
curl --quote '-SITE CHMOD 0700 ros' --upload-file /var/tftpboot/ros ftp://192.168.15.100:21
```
The transfer completes successfully, but the curl complains: `curl: (21) QUOT string not accepted: SITE CHMOD 0700 ros`
```
ftp> quote SITE CHMOD 0777 ros
---> SITE CHMOD 0777 ros
550 Some errors occurred while changing file permissions.
```

I want to upload the file and mark it as executable automatically. Maybe there is some another way to do it, but for instance umask is not supported. How this can be done?

**Comment by kingk85** [comment]
Hello,
Thank you for your e-mail, some commands need to be improved, I will take a
note from your experience.

Anyway you can use the following command I have verified that it works:
curl -Q 'SITE CHMOD 400 /home/ugo/Scrivania/14.3.0.0.tar.bz2' '
***@***.***:21'

Even if you will get an error because the QUOT command is not implemented
you can change the file permissions.

Regards
Ugo

Il giorno mar 23 mar 2021 alle ore 12:25 Alexey Suslov <
***@***.***> ha scritto:

**Comment by Str1ker17** [comment]
You were right, the permissions were changed despite 550 error.
So all I need is to ignore errors in curl by adding a second modifier `*` to the `--quote` parameter:
```
curl --quote '-*SITE CHMOD 0700 ros' --upload-file /var/tftpboot/ros ftp://192.168.15.100:21
```
This works well.
Thank you for the advice and your effort over embedded FTP server!
