### ISSUE TITLE
running as non-root user

### ISSUE THREAD

**Issue by neilgrant** [kingk85/uFTP#5]
Hi, 
I wondered if it is possible to run this as a non-root user? Obviously this would need to be on a non-privileged port.

Thanks
Neil

**Comment by Str1ker17** [comment]
Hello. I'm not a uFTP maintainer, however, did you try it yourself?
Let's try to create a user, enter its shell, then write down [`uftpd.cfg`](https://www.uftpserver.com/wiki/uftp-server-configuration). You need to set a non-privileged port: change
```
FTP_PORT = 21
```
to something else higher than 1023.

If you don't want to enter user's shell, you can use `sudo -u <username>` or `su -l <username>` to run a single process with <username> rights.

**Comment by jarpatus** [comment]
I realize this issue is years old but came here to look up how to run this non-root and found this issue... Turns out that runnin uFTP as non-root does not work if SINGLE_INSTANCE has been set to true (as it is by default) because it tries to read/write /var/run/uFTP.pid . Change SINGLE_INSTANCE to false or modify LOCKFILE in library/daemon.c to point somewhere else. 

Preferrably this should be setting in conf file?

**Comment by kingk85** [comment]
Hello,

To run uFTP as a non root user you have to:
Change the port above 1024, for instance port 2000 will work, linux doesn't
allow non root processes to use standard ports.

then in the config file that should be copied in the same directory of the
binary file change the following settings:

SINGLE_INSTANCE = false
#Allow only one server instance (true or false)

DAEMON_MODE = false
#Run in background, daemon mode ok

in the user section of the config file set the configuration to match
GROUP_NAME_OWNER_X and USER_NAME_OWNER_X the user will execute the server,
for instance i have an user ugo and group ugo:

#USERS
#START FROM USER 0 TO XXX
USER_0 = username
PASSWORD_0 = password
HOME_0 = /home/ugo/
GROUP_NAME_OWNER_0 = ugo
USER_NAME_OWNER_0 = ugo


Best Regards
Ugo

Il giorno dom 2 lug 2023 alle ore 11:46 Jari Eskelinen <
***@***.***> ha scritto:

**Comment by badbeef** [comment]
Thank you. 

Please put the instruction in the Documentation wiki page. Being able to start FTP server as a non-root user is a major appeal of portable apps. Otherwise, we could just use the default ftp server that comes with the distribution.

Also, the uFTP program doesn't seem to print out any errors / debugs. Printing some errors when it is not able to perform certain system calls would be helpful.

**Comment by kingk85** [comment]
Hello,
Thank you for your response.
I will create a wiki page for this use case using uFTP as a non root user.
In the latest release logs are available you can set a writable folder in
the configuration file and this should work for you.

Kind Regards
Ugo Cirmignani

Il giorno dom 15 set 2024 alle ore 06:23 badbeef ***@***.***>
ha scritto:
